[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_test = "6NZLquyhsNFA9GvspjQJ26Am1PzCdkhqdKtpHbtCjyDH"

[programs.localnet]
nft_test = "DcLkKey6fJ8jGLNRoyWhXxYAXePoGVGwWqJB54fjYYHw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
